//! Character data: the search index, per-character stroke data, and lookup.
//!
//! Both are generated by `scripts/build-data.py` and served as static files from
//! `public/data/`. The index is fetched once and kept in a context signal for the
//! lifetime of the app; individual characters are fetched on demand and memoised.

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

use serde::Deserialize;

/// Where the generated data lives, relative to the site root.
const DATA_ROOT: &str = "/data";

/// Rare characters have no vendored stroke file (see `scripts/build-data.py`), so
/// they fall back to the jsDelivr mirror of hanzi-writer-data. That package is
/// derived from the same Make Me a Hanzi graphics, so the coordinate space and
/// median format are identical.
const CDN_ROOT: &str = "https://cdn.jsdelivr.net/npm/hanzi-writer-data@2.0";

/// Most results anyone scrolls. Search is linear over ~9.5k entries, so capping
/// keeps the slowest tier (definition substring matching) bounded.
const SEARCH_LIMIT: usize = 60;

// ── Search index ────────────────────────────────────────────────────────────

/// The on-disk index, stored columnar: one entry per character at the same offset
/// in every array. Cheaper to parse and noticeably smaller than an array of
/// objects, which matters because this is ~518 KB.
#[derive(Deserialize)]
struct RawIndex {
    count: usize,
    ranked: usize,
    bundled: usize,
    chars: String,
    pinyin: Vec<String>,
    keys: Vec<String>,
    gloss: Vec<String>,
    strokes: Vec<u8>,
    hsk: Vec<u8>,
    radical: String,
}

/// One character's summary, enough to render a search result or a grid tile.
#[derive(Clone, PartialEq)]
pub struct Summary {
    pub glyph: char,
    /// Primary reading, with tone marks. Empty for characters with no reading.
    pub pinyin: String,
    /// Space-separated toneless readings, for matching typed pinyin.
    keys: String,
    pub gloss: String,
    pub stroke_count: u8,
    /// HSK 3.0 band, 1-7 where 7 covers the merged 7-9 range. 0 means not on the
    /// HSK list.
    pub hsk: u8,
    pub radical: char,
}

impl Summary {
    pub fn hsk_label(&self) -> Option<String> {
        match self.hsk {
            0 => None,
            7 => Some("HSK 7-9".to_string()),
            band => Some(format!("HSK {band}")),
        }
    }
}

pub struct Index {
    entries: Vec<Summary>,
    positions: HashMap<char, usize>,
    /// How many of `entries`, from the front, have a vendored stroke file.
    bundled: usize,
    ranked: usize,
}

impl Index {
    /// Fetch and parse the index. Called once, from the app root.
    pub async fn load() -> Result<Self, String> {
        let url = format!("{DATA_ROOT}/index.json");
        let raw: RawIndex = fetch_json(&url).await?;

        let glyphs: Vec<char> = raw.chars.chars().collect();
        let radicals: Vec<char> = raw.radical.chars().collect();
        if glyphs.len() != raw.count {
            return Err(format!(
                "index declares {} characters but lists {}",
                raw.count,
                glyphs.len()
            ));
        }

        let entries: Vec<Summary> = glyphs
            .iter()
            .enumerate()
            .map(|(i, &glyph)| Summary {
                glyph,
                pinyin: raw.pinyin.get(i).cloned().unwrap_or_default(),
                keys: raw.keys.get(i).cloned().unwrap_or_default(),
                gloss: raw.gloss.get(i).cloned().unwrap_or_default(),
                stroke_count: raw.strokes.get(i).copied().unwrap_or(0),
                hsk: raw.hsk.get(i).copied().unwrap_or(0),
                radical: radicals.get(i).copied().unwrap_or(glyph),
            })
            .collect();

        let positions = entries
            .iter()
            .enumerate()
            .map(|(i, e)| (e.glyph, i))
            .collect();

        Ok(Self {
            entries,
            positions,
            bundled: raw.bundled,
            ranked: raw.ranked,
        })
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn ranked(&self) -> usize {
        self.ranked
    }

    pub fn get(&self, glyph: char) -> Option<&Summary> {
        self.positions.get(&glyph).map(|&i| &self.entries[i])
    }

    /// True when the character's stroke data ships with the app rather than
    /// needing the CDN.
    fn is_bundled(&self, glyph: char) -> bool {
        self.positions
            .get(&glyph)
            .is_some_and(|&i| i < self.bundled)
    }

    /// The `n` most useful characters. `entries` is ordered by HSK band then
    /// corpus frequency, so this is just the front of the list.
    pub fn most_common(&self, n: usize) -> Vec<Summary> {
        self.entries.iter().take(n).cloned().collect()
    }

    pub fn lookup_all(&self, glyphs: &[char]) -> Vec<Summary> {
        glyphs
            .iter()
            .filter_map(|&c| self.get(c))
            .cloned()
            .collect()
    }

    /// Every character on an HSK band, in teaching order.
    pub fn by_hsk_band(&self, band: u8) -> Vec<Summary> {
        self.entries
            .iter()
            .filter(|e| e.hsk == band)
            .cloned()
            .collect()
    }

    /// Search by character, pinyin, or English definition.
    ///
    /// Tiers are tried in order and the first that produces anything wins, so
    /// typing a character never buries it under definition matches:
    ///
    /// 1. Any Han characters in the query, returned in the order typed. This is
    ///    what makes pasting a whole sentence useful.
    /// 2. Toneless pinyin — exact syllable matches first, then prefixes.
    /// 3. Substring of the English gloss.
    pub fn search(&self, query: &str) -> Vec<Summary> {
        let query = query.trim();
        if query.is_empty() {
            return Vec::new();
        }

        let mut seen: Vec<char> = Vec::new();
        for ch in query.chars() {
            if self.positions.contains_key(&ch) && !seen.contains(&ch) {
                seen.push(ch);
            }
        }
        if !seen.is_empty() {
            return self.lookup_all(&seen);
        }

        let key = toneless(query);
        if !key.is_empty() {
            let mut exact = Vec::new();
            let mut prefix = Vec::new();
            for entry in &self.entries {
                if entry.keys.split(' ').any(|k| k == key) {
                    exact.push(entry.clone());
                } else if entry
                    .keys
                    .split(' ')
                    .any(|k| !k.is_empty() && k.starts_with(&key))
                {
                    prefix.push(entry.clone());
                }
                if exact.len() >= SEARCH_LIMIT {
                    break;
                }
            }
            exact.extend(prefix);
            exact.truncate(SEARCH_LIMIT);
            if !exact.is_empty() {
                return exact;
            }
        }

        if query.chars().count() < 2 {
            return Vec::new();
        }
        let needle = query.to_lowercase();
        self.entries
            .iter()
            .filter(|e| e.gloss.to_lowercase().contains(&needle))
            .take(SEARCH_LIMIT)
            .cloned()
            .collect()
    }
}

/// "hǎo" -> "hao", "lǜ" -> "lv". Every Chinese IME types ü as v, so the index
/// stores it that way and queries are folded to match.
fn toneless(text: &str) -> String {
    text.chars()
        .filter_map(|c| match c {
            'ā' | 'á' | 'ǎ' | 'à' | 'a' | 'A' => Some('a'),
            'ē' | 'é' | 'ě' | 'è' | 'e' | 'E' => Some('e'),
            'ī' | 'í' | 'ǐ' | 'ì' | 'i' | 'I' => Some('i'),
            'ō' | 'ó' | 'ǒ' | 'ò' | 'o' | 'O' => Some('o'),
            'ū' | 'ú' | 'ǔ' | 'ù' | 'u' | 'U' => Some('u'),
            'ǖ' | 'ǘ' | 'ǚ' | 'ǜ' | 'ü' | 'v' | 'V' => Some('v'),
            c if c.is_ascii_alphabetic() => Some(c.to_ascii_lowercase()),
            _ => None,
        })
        .collect()
}

// ── Per-character data ──────────────────────────────────────────────────────

/// A single stroke's outline and centreline, in Make Me a Hanzi's coordinate
/// space. See [`crate::components::stroke_player`] for the transform that maps it
/// into an SVG viewBox.
#[derive(Deserialize, Clone, PartialEq)]
pub struct Graphics {
    /// Closed, filled outlines — one per stroke, in stroke order. These are
    /// filled, never stroked.
    pub strokes: Vec<String>,
    /// Centreline polylines, index-aligned with `strokes`. Used to drive the
    /// drawing animation.
    pub medians: Vec<Vec<[f64; 2]>>,
}

#[derive(Clone, PartialEq)]
pub struct Character {
    pub glyph: char,
    pub pinyin: Vec<String>,
    pub definition: String,
    pub radical: char,
    /// Ideographic Description Sequence, e.g. "⿰女子" for 好. Empty when Make
    /// Me a Hanzi has no decomposition.
    pub decomposition: String,
    pub hsk: u8,
    pub graphics: Graphics,
}

impl Character {
    pub fn stroke_count(&self) -> usize {
        self.graphics.strokes.len()
    }

    /// Definition senses, which Make Me a Hanzi separates with semicolons.
    pub fn senses(&self) -> Vec<&str> {
        self.definition
            .split(';')
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .collect()
    }

    pub fn hsk_label(&self) -> Option<String> {
        match self.hsk {
            0 => None,
            7 => Some("HSK 7-9".to_string()),
            band => Some(format!("HSK {band}")),
        }
    }
}

/// The vendored per-character file: metadata and graphics together.
#[derive(Deserialize)]
struct RawCharacter {
    #[serde(rename = "char")]
    glyph: String,
    #[serde(default)]
    pinyin: Vec<String>,
    #[serde(default)]
    definition: String,
    #[serde(default)]
    radical: String,
    #[serde(default)]
    decomposition: String,
    #[serde(default)]
    hsk: u8,
    strokes: Vec<String>,
    medians: Vec<Vec<[f64; 2]>>,
}

thread_local! {
    /// Parsed characters, kept for the session. Character pages are revisited
    /// constantly while browsing the "same radical" grid.
    static CACHE: RefCell<HashMap<char, Rc<Character>>> = RefCell::new(HashMap::new());
}

/// Load one character, preferring the vendored file and falling back to the CDN
/// mirror for the rare tail.
///
/// `summary` supplies the metadata when only graphics come back from the CDN.
pub async fn load_character(
    glyph: char,
    index: &Index,
    summary: Option<&Summary>,
) -> Result<Rc<Character>, String> {
    if let Some(hit) = CACHE.with(|c| c.borrow().get(&glyph).cloned()) {
        return Ok(hit);
    }

    let character = if index.is_bundled(glyph) {
        let raw: RawCharacter = fetch_json(&format!("{DATA_ROOT}/char/{:05x}.json", glyph as u32))
            .await
            .map_err(|e| format!("could not load stroke data for {glyph}: {e}"))?;
        Character {
            glyph: raw.glyph.chars().next().unwrap_or(glyph),
            pinyin: raw.pinyin,
            definition: raw.definition,
            radical: raw.radical.chars().next().unwrap_or(glyph),
            decomposition: raw.decomposition,
            hsk: raw.hsk,
            graphics: Graphics {
                strokes: raw.strokes,
                medians: raw.medians,
            },
        }
    } else {
        // The CDN carries graphics only, so metadata comes from the index.
        let mut url = String::from(CDN_ROOT);
        url.push('/');
        url.push_str(&crate::url::encode(&glyph.to_string()));
        url.push_str(".json");
        let graphics: Graphics = fetch_json(&url)
            .await
            .map_err(|e| format!("could not load stroke data for {glyph}: {e}"))?;
        Character {
            glyph,
            pinyin: summary
                .map(|s| s.pinyin.clone())
                .filter(|p| !p.is_empty())
                .into_iter()
                .collect(),
            definition: summary.map(|s| s.gloss.clone()).unwrap_or_default(),
            radical: summary.map_or(glyph, |s| s.radical),
            decomposition: String::new(),
            hsk: summary.map_or(0, |s| s.hsk),
            graphics,
        }
    };

    if character.graphics.strokes.is_empty() {
        return Err(format!("{glyph} has no stroke data"));
    }
    if character.graphics.strokes.len() != character.graphics.medians.len() {
        return Err(format!("{glyph} has mismatched strokes and medians"));
    }

    let character = Rc::new(character);
    CACHE.with(|c| c.borrow_mut().insert(glyph, character.clone()));
    Ok(character)
}

async fn fetch_json<T: serde::de::DeserializeOwned>(url: &str) -> Result<T, String> {
    let response = gloo_net::http::Request::get(url)
        .send()
        .await
        .map_err(|e| e.to_string())?;
    if !response.ok() {
        return Err(format!("HTTP {}", response.status()));
    }
    response.json::<T>().await.map_err(|e| e.to_string())
}
