//! The HSK course: levels, the units they are split into, and the words a unit
//! teaches.
//!
//! Separate from [`crate::data`], which knows about characters. A character has a
//! band — the level at which HSK first introduces it — and that is all the
//! dictionary needs. The course is about *words*: 你好 is a unit's headword, but
//! it is not a character and has no stroke data of its own.
//!
//! Generated by `scripts/build-hsk-data.py` from the React app's course files;
//! see the README's Data section. `index.json` is under a kilobyte and the hub
//! needs it immediately, so it is compiled in. The levels are a hundred KB each
//! and are fetched when somebody opens one.

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

use serde::Deserialize;

use crate::data::DATA_ROOT;

/// HSK 3.0 bands 1-6, which is what the course covers. Characters go up to the
/// merged 7-9 band, but there is no unit vocabulary for it.
pub const LEVELS: [u8; 6] = [1, 2, 3, 4, 5, 6];

/// A gloss long enough to be a real answer on a list row, short enough not to
/// wrap three times on a phone.
const MAX_GLOSS: usize = 140;

/// How many meanings a gloss keeps. The rest are on the character pages.
const MAX_MEANINGS: usize = 3;

const COURSE_INDEX: &str = include_str!("../public/data/hsk/index.json");

pub fn is_level(level: u8) -> bool {
    (1..=6).contains(&level)
}

// ── The course index ────────────────────────────────────────────────────────

/// What a level holds, without loading it. Drives the hub's level cards.
#[derive(Deserialize, Clone, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct LevelSummary {
    pub level: u8,
    pub unit_count: usize,
    pub word_count: usize,
    pub char_count: usize,
}

#[derive(Deserialize)]
struct CourseIndex {
    levels: Vec<LevelSummary>,
}

thread_local! {
    /// Parsed once. A malformed index is a build error, not a runtime one — the
    /// file is generated and compiled in — so this panics rather than adding a
    /// loading state to every page that shows a level count.
    static SUMMARIES: Rc<Vec<LevelSummary>> = Rc::new(
        serde_json::from_str::<CourseIndex>(COURSE_INDEX)
            .expect("public/data/hsk/index.json is not a course index")
            .levels,
    );
}

pub fn summaries() -> Rc<Vec<LevelSummary>> {
    SUMMARIES.with(Rc::clone)
}

pub fn summary(level: u8) -> Option<LevelSummary> {
    summaries().iter().find(|s| s.level == level).cloned()
}

pub fn total_words() -> usize {
    summaries().iter().map(|s| s.word_count).sum()
}

pub fn total_units() -> usize {
    summaries().iter().map(|s| s.unit_count).sum()
}

// ── One level ───────────────────────────────────────────────────────────────

/// A unit: a five-minute session's worth of vocabulary, grouped by theme.
#[derive(Deserialize, Clone, PartialEq)]
pub struct Unit {
    /// `"3-07"` — level and position. Stable across rebuilds of the same data,
    /// so a list can remember which unit it came from.
    pub id: String,
    pub title: String,
    /// Theme the unit was grouped under, e.g. `"food"`.
    #[serde(default)]
    pub topic: String,
    /// Headwords, in teaching order. Every one has an entry in the level's word
    /// map; the generator drops units where that is not true.
    pub words: Vec<String>,
}

impl Unit {
    /// The position within its level: `"07"` for `"3-07"`. What the URL and the
    /// unit rows show, since the level is already in both.
    pub fn number(&self) -> &str {
        self.id.split_once('-').map_or(self.id.as_str(), |(_, n)| n)
    }
}

/// A course word, resolved against its level's word map.
#[derive(Clone, PartialEq)]
pub struct Word {
    /// Simplified headword: one character or several.
    pub word: String,
    pub pinyin: String,
    /// Up to three meanings, joined — see [`gloss`].
    pub gloss: String,
    pub level: u8,
}

#[derive(Deserialize, Clone)]
struct Entry {
    #[serde(default)]
    pinyin: String,
    #[serde(default)]
    meanings: Vec<String>,
}

/// The on-disk level file. Unknown fields are ignored, so the untrimmed course
/// files from the React app can be dropped in unchanged.
#[derive(Deserialize)]
struct RawLevel {
    level: u8,
    units: Vec<Unit>,
    words: HashMap<String, Entry>,
}

pub struct Level {
    pub level: u8,
    pub units: Vec<Unit>,
    words: HashMap<String, Entry>,
}

impl Level {
    /// Find a unit by the id in a URL. Accepts the position on its own (`"07"`,
    /// which is what this app's routes carry) as well as the full id (`"3-07"`,
    /// which is what the data and an imported list use).
    pub fn unit(&self, id: &str) -> Option<&Unit> {
        self.units
            .iter()
            .find(|u| u.id == id || u.number() == id)
    }

    pub fn position_of(&self, unit: &Unit) -> Option<usize> {
        self.units.iter().position(|u| u.id == unit.id)
    }

    /// The unit before or after this one, for walking a level in order.
    pub fn neighbours(&self, unit: &Unit) -> (Option<&Unit>, Option<&Unit>) {
        match self.position_of(unit) {
            Some(at) => (
                at.checked_sub(1).and_then(|i| self.units.get(i)),
                self.units.get(at + 1),
            ),
            None => (None, None),
        }
    }

    pub fn word(&self, headword: &str) -> Option<Word> {
        self.words.get(headword).map(|entry| Word {
            word: headword.to_string(),
            pinyin: entry.pinyin.clone(),
            gloss: gloss(&entry.meanings),
            level: self.level,
        })
    }

    /// A unit's words, in teaching order.
    pub fn unit_words(&self, unit: &Unit) -> Vec<Word> {
        unit.words.iter().filter_map(|w| self.word(w)).collect()
    }

    /// The first few headwords, for a unit row's preview.
    pub fn preview(&self, unit: &Unit, n: usize) -> String {
        unit.words
            .iter()
            .take(n)
            .map(String::as_str)
            .collect::<Vec<_>>()
            .join("  ")
    }
}

/// Up to three meanings, joined with semicolons and capped.
///
/// One meaning is often too thin to recognise a word by — 会 is "can", but also
/// "meeting" — and the full CC-CEDICT entry runs to a paragraph.
fn gloss(meanings: &[String]) -> String {
    let joined = meanings
        .iter()
        .take(MAX_MEANINGS)
        .map(|m| m.trim())
        .filter(|m| !m.is_empty())
        .collect::<Vec<_>>()
        .join("; ");
    if joined.chars().count() <= MAX_GLOSS {
        return joined;
    }
    let mut short: String = joined.chars().take(MAX_GLOSS - 1).collect();
    short.truncate(short.trim_end().len());
    short.push('…');
    short
}

/// The distinct characters in a run of words, in first-seen order. What lets a
/// unit or a list offer its characters for stroke practice.
pub fn characters<'a>(words: impl IntoIterator<Item = &'a str>) -> Vec<char> {
    let mut seen = Vec::new();
    for word in words {
        for ch in word.chars() {
            if !seen.contains(&ch) {
                seen.push(ch);
            }
        }
    }
    seen
}

thread_local! {
    /// Loaded levels, kept for the session. A level is ~100 KB of JSON and gets
    /// revisited every time somebody steps between its units.
    static CACHE: RefCell<HashMap<u8, Rc<Level>>> = RefCell::new(HashMap::new());
}

pub async fn load_level(level: u8) -> Result<Rc<Level>, String> {
    if !is_level(level) {
        return Err(format!("The course covers HSK 1 to 6, not {level}."));
    }
    if let Some(hit) = CACHE.with(|c| c.borrow().get(&level).cloned()) {
        return Ok(hit);
    }

    let url = format!("{DATA_ROOT}/hsk/level-{level}.json");
    let raw: RawLevel = crate::data::fetch_json(&url)
        .await
        .map_err(|e| format!("Could not load HSK {level}: {e}"))?;
    if raw.level != level {
        return Err(format!(
            "The file for HSK {level} declares level {}.",
            raw.level
        ));
    }

    let loaded = Rc::new(Level {
        level: raw.level,
        units: raw.units,
        words: raw.words,
    });
    CACHE.with(|c| c.borrow_mut().insert(level, loaded.clone()));
    Ok(loaded)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_compiled_index_covers_every_level() {
        let summaries = summaries();
        assert_eq!(summaries.len(), LEVELS.len());
        for level in LEVELS {
            let found = summary(level).expect("a summary per level");
            assert!(found.unit_count > 0 && found.word_count > 0);
        }
    }

    #[test]
    fn a_unit_id_splits_into_its_position() {
        let unit = Unit {
            id: "3-07".to_string(),
            title: "Food & drink".to_string(),
            topic: "food".to_string(),
            words: vec!["菜".to_string()],
        };
        assert_eq!(unit.number(), "07");
    }

    #[test]
    fn a_gloss_joins_the_first_meanings_and_stays_short() {
        let meanings = ["can".to_string(), "meeting".to_string(), "to know".to_string()];
        assert_eq!(gloss(&meanings), "can; meeting; to know");

        let long = vec!["x".repeat(200)];
        let cut = gloss(&long);
        assert!(cut.ends_with('…'));
        assert_eq!(cut.chars().count(), MAX_GLOSS);
    }

    #[test]
    fn characters_are_distinct_and_in_first_seen_order() {
        assert_eq!(characters(["你好", "好"]), vec!['你', '好']);
    }
}
